### ISSUE TITLE
Update dependency to nix-0.11

### ISSUE THREAD

**Issue by paride** [oconnor663/os_pipe.rs#13]
I will have to bug you again. Could you bump the dependency on nix to version 0.11 and tag a new release, as you did for shared_child?

**Comment by oconnor663** [comment]
Sure thing! Always happy to find out people are using the libs :)

**Comment by oconnor663** [comment]
If you happen to notice that all my Travis runs are failing today, it's due to this: https://github.com/rust-lang/rust/issues/52686

**Comment by oconnor663** [comment]
Just published os_pipe v0.6.2.

**Comment by paride** [comment]
Thanks again. I made two Debian packages for the libraries and, after approval, they will become part of the distribution. I did need them as they are dependencies of other software I want to package, but I'm sure they will useful to other people too.

**Comment by oconnor663** [comment]
Out of curiosity, what other software is calling into `os_pipe`? Is it via `duct`?

**Comment by paride** [comment]
Yes, the dependency comes from `duct`.

**Comment by oconnor663** [comment]
@paride I've published another new version (0.7.0) with an overhaul to the lesser-used parts of the API.
