### ISSUE TITLE
README clarification regarding dropping writers before reading

### ISSUE THREAD

**Issue by eze-works** [oconnor663/os_pipe.rs#34]
Hello! 

Thanks for the work you put into the implementation of this library and the associated documentation.

This blurb on the README confused me at first:

> Pipe reads will block waiting for input as long as there's at least one writer still open. If you forget to close a writer, reads will block forever. This includes writers that you give to child processes.

I thought this meant: "Any reads from the reader end of the pipe will block until writers are dropped"... which is odd. Why would I have to wait to read anything at all until the writers are dropped 🤔 ??

I then figured out that it is actually saying:
"Reading from the reader end of the pipe will see an EOF once all writer ends have been dropped." 

I confirmed that is the case with this snippet:

```rust
use std::io::Read;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut echo_cmd = std::process::Command::new("echo");
    echo_cmd.args(&["hello", " world"]);

    let (mut reader, writer) = os_pipe::pipe()?;
    echo_cmd.stdout(writer);

    let mut handle = echo_cmd.spawn()?;

    // We never break out of this loop, but the text "hello world" is still printed
    loop {
        let mut buf = [0u8; 1];
        match reader.read(&mut buf) {
            Ok(0) => break,
            Ok(_) => {
                println!("{}", String::from_utf8_lossy(&buf));
            }
            Err(e) => {
                eprintln!("{e}");
                break;
            }
        }
    }
    Ok(())
}
```

This made me wonder if that bullet point could be tweaked a bit. Maybe something like:

> A pipe reader will only reach its "end-of-file" when all corresponding writers have been dropped. 
> Note: When using pipes with `std::process::Command`, you might have to manually drop the `Command` struct to ensure this happens

I imagine you've thought about this waay more than I have though, so feel free to disregard this suggestion. I filled it mostly so anyone searching that was confused as I was potentially finds some clarity.

**Comment by oconnor663** [comment]
Good point! What do you think of this version:

> Pipe reads block until some bytes are written or all writers are closed. **If you forget to close a writer, reads can block forever.** This includes writers inside a `std::process::Command` object or writers given to child processes.

**Comment by eze-works** [comment]
That makes sense to me 👍🏾  (and is probably better because this section is in the context of warning about deadlocks)

Thanks again for putting the time into this crate. It makes piping between processes so much easier.
