### ISSUE TITLE
does os_pipe support for tokio::io::copy?

### ISSUE THREAD

**Issue by ningmingxiao** [oconnor663/os_pipe.rs#35]
we often meet io::copy hang if  fd is closed on write side.

**Comment by oconnor663** [comment]
No, this crate isn't intended to work with async IO. You could probably make it work on Unix by calling `libc::fcntl` with `O_NONBLOCK` after creating the pipe, but I haven't tried it. (And if you're going to get that low-level/platform-specific, then this crate isn't really doing much for you, and it might make more sense to call `libc::pipe2` yourself instead.) There's [a comment in the Rust standard library](https://github.com/rust-lang/rust/blob/68e4d9654ea5bd3553c892a23f42b4f17b37e5f1/library/std/src/sys/pal/windows/pipe.rs#L63-L72) that discusses why these pipes cannot work with async IO on Windows ("IOCP").

**Comment by ningmingxiao** [comment]
Thank you.
